#theme: jekyll-theme-hacker
title: bnc.ee
author: Your Name
description: A short, compelling description of your website.
google_analytics: G-BT1N14HW0M
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects.html
  - title: Blog
    url: /blog.html

social:
  github: your-github-username
  twitter: your-twitter-username
  linkedin: your-linkedin-username

sass:
  load_paths: ["_sass"]