theme: jekyll-theme-hacker
title: bnc.ee
future: true
author: Your Name
description: A short, compelling description of your website.
google_analytics: G-BT1N14HW0M
remote_theme: pages-themes/hacker@v0.2.0
# Site URL and baseurl for absolute_url/relative_url filters
url: "https://bnc.ee"
baseurl: ""
permalink: /:categories/:title/
autopages: 
  enabled: true
  # Site-enabled: false

#header_pages: true
header_pages: 
  - index.md
  - about.md
  - projects.md
  - blog.md
plugins:
  - jekyll-archives
  - jekyll-paginate-v2
  - jekyll-include-cache
  - jekyll-picture-tag
  - jekyll-compose
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Blog
    url: /blog/
  - title: Search
    url: /search/

social:
  github: your-github-username
  twitter: your-twitter-username
  linkedin: your-linkedin-username

sass:
  load_paths: ["_sass"]
include:
  - _redirects

# jekyll-archives example config
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: /category/:name/
    tag: /tag/:name/

# jekyll-paginate-v2 example config
pagination:
  enabled: true
  per_page: 5
  permalink: /blog/:num/
  title: ':title - page :num'

# jekyll-picture-tag example config: responsive image presets
picture:
  source: assets/images
  output: assets/images/generated
  presets:
    default:
      widths: [320, 640, 960, 1280]
      formats: [webp, jpeg]
      attributes:
        loading: lazy
        decoding: async