#theme: jekyll-theme-hacker
title: bnc.ee
author: Your Name
description: A short, compelling description of your website.
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects.html