name: Jekyll build & validate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Cache Ruby gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-ruby-${{ matrix.ruby || '3.1' }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies
        run: |
          gem install bundler --conservative
          bundle config set path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Install system packages for image processing (libvips preferred)
        run: |
          # Install libvips (preferred) with dev headers; fall back to imagemagick on failure
          sudo apt-get update
          set -e
          echo "Attempting to install libvips..."
          if sudo apt-get install -y libvips-tools libvips-dev; then
            echo "libvips installed successfully"
          else
            echo "libvips install failed; attempting to install ImageMagick as fallback"
            sudo apt-get install -y imagemagick
            echo "ImageMagick installed (fallback)"
          fi

      - name: Check image tool versions
        run: |
          echo "=== vips (if installed) ==="
          if command -v vips >/dev/null 2>&1; then vips --version || true; else echo "vips not found"; fi
          echo "=== ImageMagick (convert) ==="
          if command -v convert >/dev/null 2>&1; then convert --version || true; else echo "convert not found"; fi

      - name: Smoke test: image processing
        id: smoke
        run: |
          set -e
          SRC=assets/images/og-image.png
          OUTDIR=assets/images/generated/ci-smoke
          mkdir -p "$OUTDIR"
          # If source exists and non-empty use it; otherwise create a tiny 1x1 PNG as fallback
          if [ -f "$SRC" ] && [ -s "$SRC" ]; then
            TEST_SRC="$SRC"
          else
            TEST_SRC="$OUTDIR/sample.png"
            echo "Creating tiny fallback PNG for smoke test: $TEST_SRC"
            echo "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg==" | base64 --decode > "$TEST_SRC"
          fi
          if command -v vips >/dev/null 2>&1; then
            echo "Running vips resize smoke test on $TEST_SRC"
            vips resize "$TEST_SRC" "$OUTDIR/test.jpg" 0.5 || (echo "vips resize failed"; exit 1)
          elif command -v convert >/dev/null 2>&1; then
            echo "Running ImageMagick convert smoke test on $TEST_SRC"
            convert "$TEST_SRC" -resize 50% "$OUTDIR/test.jpg" || (echo "convert resize failed"; exit 1)
          else
            echo "No image processing tool available (vips or convert)"; exit 1
          fi
          echo "Smoke test image created: $OUTDIR/test.jpg"
          ls -l "$OUTDIR/test.jpg" || true

      - name: Upload smoke image artifact
        if: steps.smoke.outcome == 'success' && always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-smoke-image
          path: assets/images/generated/ci-smoke/test.jpg

      - name: Build site with Jekyll
        run: bundle exec jekyll build --trace

      - name: Upload site artifact for PR preview
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: site-preview
          path: _site

      - name: Install markdownlint-cli
        run: |
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g markdownlint-cli@0.35.0

      - name: Run markdownlint
        run: |
          markdownlint "**/*.md" --config .markdownlint.yml

      - name: Validate robots.txt contains site.url
        run: |
          set -e
          URL=$(ruby -ryaml -e "puts YAML.load_file('_config.yml')['url']")
          if [ -z "$URL" ]; then
            echo "Warning: 'url' is empty in _config.yml"; exit 1
          fi
          if ! grep -q "$URL" _site/robots.txt; then
            echo "_site/robots.txt does not contain $URL"; exit 1
          fi

      - name: Validate sitemap.xml contains site.url
        run: |
          set -e
          URL=$(ruby -ryaml -e "puts YAML.load_file('_config.yml')['url']")
          if ! grep -q "$URL" _site/sitemap.xml; then
            echo "_site/sitemap.xml does not contain $URL"; exit 1
          fi

  preview:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: site-preview

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          persist-credentials: true

      - name: Copy preview into gh-pages
        run: |
          PR_NUM=${{ github.event.number }}
          mkdir -p preview/pr-${PR_NUM}
          rm -rf preview/pr-${PR_NUM}/* || true
          cp -r _site/* preview/pr-${PR_NUM}/
          git add preview/pr-${PR_NUM}
          git commit -m "Add preview for PR #${PR_NUM} [ci skip]" || echo "No changes to commit"
          git push origin gh-pages

      - name: Comment PR with preview URL
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request.number
            const repo = context.repo.repo
            const owner = context.repo.owner
            const url = `https://${owner}.github.io/${repo}/preview/pr-${pr}/`
            github.issues.createComment({ owner, repo, issue_number: pr, body: `Preview available at: ${url}` })

      - name: Cleanup old previews
        run: |
          # Remove preview directories older than PREVIEW_RETENTION_DAYS (default 7)
          RETENTION_DAYS=${{ env.PREVIEW_RETENTION_DAYS || '7' }}
          echo "Preview retention set to ${RETENTION_DAYS} days"
          NOW=$(date +%s)
          for d in preview/pr-*; do
            [ -d "$d" ] || continue
            # Try to get last git commit timestamp touching this path
            LAST_COMMIT_TS=$(git log -1 --format=%ct -- "$d" 2>/dev/null || true)
            if [ -n "$LAST_COMMIT_TS" ]; then
              AGE_DAYS=$(( (NOW - LAST_COMMIT_TS) / 86400 ))
            else
              # Fallback to directory mtime
              DIR_MTIME=$(stat -c %Y "$d")
              AGE_DAYS=$(( (NOW - DIR_MTIME) / 86400 ))
            fi
            if [ "$AGE_DAYS" -gt "$RETENTION_DAYS" ]; then
              echo "Removing old preview: $d (age ${AGE_DAYS} days)"
              git rm -r --ignore-unmatch "$d" || rm -rf "$d"
            fi
          done
          git commit -m "Cleanup old previews older than ${RETENTION_DAYS} days [ci skip]" || echo "No preview cleanup changes"
          git push origin gh-pages || echo "Push failed (check branch protection)"
